In [4]:
import numpy as np
import math
import pandas as pd
dataSet=pd.read_csv('./Automobile_insurance_fraud.csv')
dataSet

months_as_customer  age  policy_number  ... auto_year fraud_reported _c39
0                   328   48         521585  ...      2004              Y  NaN
1                   228   42         342868  ...      2007              Y  NaN
2                   134   29         687698  ...      2007              N  NaN
3                   256   41         227811  ...      2014              Y  NaN
4                   228   44         367455  ...      2009              N  NaN
..                  ...  ...            ...  ...       ...            ...  ...
995                   3   38         941851  ...      2006              N  NaN
996                 285   41         186934  ...      2015              N  NaN
997                 130   34         918516  ...      1996              N  NaN
998                 458   62         533940  ...      1998              N  NaN
999                 456   60         556080  ...      2007              N  NaN

[1000 rows x 40 columns]

In [18]:
dataSet['incident_severity'].replace({'Minor Damage': 0, 'Major Damage': 1})

0      1
1      0
2      0
3      1
4      0
      ..
995    0
996    1
997    0
998    1
999    0
Name: incident_severity, Length: 1000, dtype: object

In [5]:
def Display(mat, typ):
    for i in range(len(mat)):
        for j in range(len(mat)):
            if i>=j:
                if typ=='f':
                    print('{:.2f}'.format(mat[i][j]), end=' ')
                else:
                    print(int(mat[i][j]), end=' ')
        print()
    print()
    print()
    print()

In [6]:
def Dissimilarity(data):
    data=np.array(data)
    matrix=np.zeros((data.shape[0], data.shape[0]))
    # print('OK')
    p=data.shape[1]
    for i in range(len(data)):
        for j in range(len(data)):
            m=0
            for k in range(len(data[0])):
                if data[i][k]==data[j][k]:
                    m+=1
            matrix[i][j]=(p-m)/p
            matrix[j][i]=matrix[i][j]

    return matrix

In [7]:
mat = Dissimilarity(dataSet)

In [8]:
# ans=input('Do you want to get dissimilarity between any 2 particular data records?[Y/N]: ')
# if ans=='Y':
#     one=int(input('Enter 1st data entry: '))
#     two=int(input('Enter 2nd data entry: '))
#     print('{:.2f}'.format(mat[one-1][two-1]))

In [19]:
def BinaryDissimilarity(data, attributeName):
    data=data[attributeName]
    matrix=np.zeros((data.shape[0], data.shape[0]))
    for i in range(len(data)):
        for j in range(len(data)):
            if i>=j:
                if data[i]==data[j]:
                    matrix[i][j]=0
                else:
                    matrix[i][j]=1
                matrix[j][i]=matrix[i][j]
    return matrix

In [20]:
 mat_Indian=BinaryDissimilarity(dataSet, 'incident_severity')
# Display(mat_Indian, 'i')

In [11]:
def NominalDissimilarity(data, attributeName):
    data=data[attributeName]
    matrix=np.zeros((data.shape[0], data.shape[0]))
    for i in range(len(data)):
        for j in range(i, len(data)):
            if data[i]==data[j]:
                matrix[i][j]=0
            else:
                matrix[i][j]=1
            matrix[j][i]=matrix[i][j]
    return matrix

In [12]:
mat_Team=NominalDissimilarity(dataSet, 'policy_state')
# Display(mat, 'i')

In [13]:
def NumericDissimilarity(data, attributeName):
    data=data[attributeName]
    matrix=np.zeros((data.shape[0], data.shape[0]))
    for i in range(data.shape[0]):
        for j in range(data.shape[0]):
            if i>=j:
                matrix[i][j] = abs(data[i]-data[j])/(max(data)-min(data))
                matrix[j][i] = matrix[i][j]
    
    return matrix

In [14]:
mat_FinalPrice=NumericDissimilarity(dataSet, 'total_claim_amount')
# Display(mat, 'f')

In [28]:
dissimilarity_matrix = [mat_Indian,mat_Team, mat_FinalPrice]
# dissimilarity_matrix[1][6][4]
np.shape(dissimilarity_matrix)

(3, 1000, 1000)

In [31]:
def TotalDissimilarity(data, dissimilarity_matrix):
    data=np.array(data)
    matrix=np.zeros((data.shape[0], data.shape[0]))
    for i in range(3):
        for j in range(1000):
            n=0
            d=0
            for k in range(100):
                dell=1
                n+=dell*dissimilarity_matrix[i][j][k]
                d+=dell
            matrix[i][j]=n/d


    return matrix

In [33]:
mat=TotalDissimilarity(dataSet, dissimilarity_matrix)
Display(mat, 'f')

0.70 
0.65 0.70 
0.22 0.41 0.26 
0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0

In [39]:
# Python program to compute distance matrix

# import important libraries
import numpy as np
from scipy.spatial import distance_matrix
a = np.array([dataSet['total_claim_amount'], dataSet['injury_claim'],dataSet['property_claim'],dataSet['vehicle_claim']])
# Create the matrices
# x = np.array([[1,2],[2,1],[2,2]])
# y = np.array([[5,0],[1,2],[2,0]])
a.shape
a
b = np.array([dataSet['policy_annual_premium'], dataSet['policy_deductable'],dataSet['capital-gains'],dataSet['capital-loss']])
b.shape
b
#Display the matrices
print("matrix x:\n", a)
print("matrix y:\n", b)

 # compute the distance matrix
dist_mat = distance_matrix(a, b, p=2)

# # display distance matrix
print("Distance Matrix:\n", dist_mat)


matrix x:
 [[71610  5070 34650 ... 67500 46980  5060]
 [ 6510   780  7700 ...  7500  5220   460]
 [13020   780  3850 ...  7500  5220   920]
 [52080  3510 23100 ... 52500 36540  3680]]
matrix y:
 [[ 1406.91  1197.22  1413.14 ...  1383.49  1356.92   766.19]
 [ 1000.    2000.    2000.   ...   500.    2000.    1000.  ]
 [53300.       0.   35100.   ... 35100.       0.       0.  ]
 [    0.       0.       0.   ...     0.       0.       0.  ]]
Distance Matrix:
 [[1830056.3824205  1833362.60363301 1487504.63138775 2804987.25957891]
 [ 249112.24712005  252186.479019   1051600.51930379 1413141.85282299]
 [ 247143.99635962  249957.7182245  1055355.80488288 1409850.68177449]
 [1304255.47568787 1307787.20589399 1131226.37075874 2317120.42110461]]
